### PR TITLE
Fix #19 Introduce `CRSToCRS` class

### LINKED ISSUE #19: `RGeo::CoordSys::Proj4.transform_coords` slower in version 3.0.1 than version 2.0.1
## Issue encountered

I've tried to update to the 3.0.1 version but I've observed that using `RGeo::CoordSys::Proj4.transform_coords` to project the coordinates of my geometry was slower than the 2.0.1 version.

## Step to reproduce

Here is a minimal script to reproduce, you can uncomment to alternate between the 2 versions.

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  # gem "rgeo-proj4", "~> 3.0", ">= 3.0.1"
  gem "rgeo-proj4", "~> 2.0", ">= 2.0.1"
end

raise "RGeo::Geos is not supported" unless RGeo::Geos.supported?
puts "preferred_native_interface #{RGeo::Geos.preferred_native_interface}"
puts "rgeo-proj4 version #{RGeo::Proj4::VERSION}"
raise "proj4 is not supported" unless RGeo::CoordSys::Proj4.supported?
puts "proj4 version: #{RGeo::CoordSys::Proj4.version}"
puts "RUBY_VERSION: #{RUBY_VERSION}"
puts "RUBY_PLATFORM #{RUBY_PLATFORM}"
ws84_definition = "proj=longlat +datum=WGS84 +no_defs +type=crs"
# https://epsg.io/2154
paris_lambert_definition = "+proj=lcc +lat_1=49 +lat_2=44 +lat_0=46.5 +lon_0=3 +x_0=700000 +y_0=6600000 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs"

ws84_proj4 = RGeo::CoordSys::Proj4.create(ws84_definition)
raise "invalid ws84_definition" unless ws84_proj4

paris_lambert_proj4 = RGeo::CoordSys::Proj4.create(paris_lambert_definition)
raise "invalid paris_lambert_definition" unless paris_lambert_proj4

starting = Process.clock_gettime(Process::CLOCK_MONOTONIC)
1000.times do
  RGeo::CoordSys::Proj4.transform_coords(ws84_proj4, paris_lambert_proj4, 784020.1897824854, 6722964.293806808, nil)
end
puts "Processed in #{Process.clock_gettime(Process::CLOCK_MONOTONIC) - starting}"
```

With 2.0.1
```
preferred_native_interface capi
rgeo-proj4 version 2.0.1
proj4 version: 721
RUBY_VERSION: 2.6.6
RUBY_PLATFORM x86_64-darwin19
Processed in 0.0032739999987825286
```

With 3.0.1
```
preferred_native_interface capi
rgeo-proj4 version 3.0.1
proj4 version: 7.2.1
RUBY_VERSION: 2.6.6
RUBY_PLATFORM x86_64-darwin19
Processed in 1.5407219999979134
```

## Versions
- Proj: `7.2.1`
- Ruby: `ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin19]`
- OS: macOS Catalina, Version 10.15.7,  `x86_64-darwin19`
image

## Note

I've tried to use WKT definition as well, it was faster but it was still slower than the `2.0.1`  version
```
 paris_lambert_definition = <<~EOS
      PROJCS["RGF93 / Lambert-93",
          GEOGCS["RGF93",
              DATUM["Reseau_Geodesique_Francais_1993",
                  SPHEROID["GRS 1980",6378137,298.257222101,
                      AUTHORITY["EPSG","7019"]],
                  TOWGS84[0,0,0,0,0,0,0],
                  AUTHORITY["EPSG","6171"]],
              PRIMEM["Greenwich",0,
                  AUTHORITY["EPSG","8901"]],
              UNIT["degree",0.0174532925199433,
                  AUTHORITY["EPSG","9122"]],
              AUTHORITY["EPSG","4171"]],
          PROJECTION["Lambert_Conformal_Conic_2SP"],
          PARAMETER["standard_parallel_1",49],
          PARAMETER["standard_parallel_2",44],
          PARAMETER["latitude_of_origin",46.5],
          PARAMETER["central_meridian",3],
          PARAMETER["false_easting",700000],
          PARAMETER["false_northing",6600000],
          UNIT["metre",1,
              AUTHORITY["EPSG","9001"]],
          AXIS["X",EAST],
          AXIS["Y",NORTH],
          AUTHORITY["EPSG","2154"]]
    EOS

    ws84_definition = <<~EOS
      GEOGCS["WGS 84",
           DATUM["WGS_1984",
                 SPHEROID["WGS 84",6378137,298.257223563,
                          AUTHORITY["EPSG","7030"]],
                 AUTHORITY["EPSG","6326"]],
           PRIMEM["Greenwich",0,
                  AUTHORITY["EPSG","8901"]],
           UNIT["degree",0.0174532925199433,
                AUTHORITY["EPSG","9122"]],
           AUTHORITY["EPSG","4326"]]
    EOS
```

Result
```
preferred_native_interface capi
rgeo-proj4 version 3.0.1
proj4 version: 7.2.1
RUBY_VERSION: 2.6.6
RUBY_PLATFORM x86_64-darwin19
Processed in 0.4099999999998545
```

## Docker image to reproduce
Here is a gist with a docker image where I've reproduced the issue with proj version:`8.1.0`

https://gist.github.com/x4d3/1dff5f2348a0a6ec1a6fd440d0d64ac7

### PR DESCRIPTION
**Pull request by x4d3**
In newer versions of proj, you need to create a crs_to_crs projection and then transform coordinates with that, whereas in older versions you would pass 2 separate CRS's into the transform function.

This PR:
- Create a new class `RGeo::CoordSys::CRSToCRS` that is instantiated from 2 `RGeo::CoordSys::Proj4` objects and stores the crs_to_crs.
- Create a singleton class `RGeo::CoordSys::CRSStore` that maps some combination of Proj4 objects to a `CRSToCRS` object.
When running transform_coords, check the `CRSStore `to see if the mapping exists, if not create it and store it, else get it.
- Change the underlying C function to accept the `crs_to_crs` instead of 2 projections and just transform the coordinates

Fix #19

### CODE REVIEW

**Review by keithdoggett — APPROVED** [review]
Thanks @x4d3 this is awesome! I just left one stylistic note in the tests.

I think it probably makes sense to break up the files a little bit since they're getting kind of big, but I can do that once this is merged. There are a couple of other little things I should do first.

I'll run the tests now, but they won't pass without the fixes in #21, so we can just note that those 6 tests will fail and merge anyways once approved or rebase once #21 is in master.

**Comment by x4d3** [comment]
@keithdoggett I've moved `crs_to_crs` to its own file, but of course feel free to reorganise as you see fit :)

File: lib/rgeo/coord_sys/crs_to_crs.rb [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+
+require "singleton"
+module RGeo
+  module CoordSys
+    # This is a Ruby wrapper around a proj crs_to_crs
+    # A crs_to_crs transformation object that is a pipeline between two known coordinate reference systems.
+    # https://proj.org/development/reference/functions.html#c.proj_create_crs_to_crs
+    class CRSToCRS
+      def transform_coords(x, y, z)
+        _transform_coords(x, y, z)
```
Comment (BuonOmo) [inline lib/rgeo/coord_sys/crs_to_crs.rb:11]: I'm not sure why we need this?

It might be about documenting the code however there is no method documentation here and you could do it in C: https://ruby.github.io/rdoc/RDoc/Parser/C.html

File: test/test_helper.rb [hunk 2]
```diff
@@ -5,3 +5,9 @@
 require "common/factory_tests"
 require "psych"
 require "pry-byebug"
+
+def assert_close_enough(a, b)
+  delta = Math.sqrt(a * a + b * b) * 0.00000001
+  delta = 1e-7 if delta < 1e-7
```
Comment (BuonOmo) [inline test/test_helper.rb:11]: This seems smart but IDK why, could you explain it to me ? :)

And maybe add a method comment I guess

**Review by BuonOmo — APPROVED** [review]
Nothing blocking for me, I like the way you code 🙂

File: test/test_helper.rb (hunk 2 above)
Comment (x4d3) [reply test/test_helper.rb:11]: Method was already there, I've just moved it :).
My understanding is that it's computing some kind of distance to make it positive. But I have to admit it kind of looks odd.

File: lib/rgeo/coord_sys/crs_to_crs.rb (hunk 1 above)
Comment (x4d3) [reply lib/rgeo/coord_sys/crs_to_crs.rb:11]: Technically you are right, there is no need to redefine it.

But I followed the convention that the C methods should be very private and prefixed by "_" and have the public method `transform_coords` declared in Ruby, so that's it's easier to find.
Agreed I should add documentation and will do.

File: test/test_helper.rb (hunk 2 above)
Comment (x4d3) [reply test/test_helper.rb]: I've documented the method and simplified it

**Comment by x4d3** [comment]
@keithdoggett @BuonOmo I've applied your comment and rebased the PR.
Please have another review.

**Review by BuonOmo — COMMENTED** [review]
Well LGTM still :)

**Comment by keithdoggett** [comment]
Thanks for the work @x4d3! I'll get a release out with this soon.
